# example netlify.toml
[build]
  command = "yarn run build"
  functions = "netlify/functions"
  publish = "build"

  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/

[[redirects]]
  from = "/core-concepts/*"
  to = "/learn"
  status = 301
  force = false

[[redirects]]
  from = "/nodes/*"
  to = "/validate/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/state-channels/*"
  to = "/metagraphs"
  status = 301
  force = false

[[redirects]]
  from = "/statechannels/*"
  to = "/metagraphs"
  status = 301
  force = false

[[redirects]]
  from = "/validators"
  to = "/validate"
  status = 301
  force = false

[[redirects]]
  from = "/sdk/frameworks/*"
  to = "/sdk/metagraph-framework"
  status = 301
  force = false
