module.exports = {
  docs: [
    { type: "autogenerated", dirName: "." },
    {
      type: "category",
      label: "Resources",
      items: [
        {
          type: "link",
          label: "Stargazer Github",
          href: "https://github.com/StardustCollective/stargazer-wallet-ext",
        },
        {
          type: "link",
          label: "Stargazer Connector Github",
          href: "https://github.com/StardustCollective/stargazer-wallet-connector",
        },
        {
          type: "link",
          label: "Stargazer Demos Github",
          href: "https://github.com/StardustCollective/stargazer-wallet-demos",
        },
        {
          type: "link",
          label: "Stargazer Chrome",
          href: "https://chrome.google.com/webstore/detail/stargazer-wallet/pgiaagfkgcbnmiiolekcfmljdagdhlcm",
        },
        {
          type: "link",
          label: "Stargazer Android",
          href: "https://play.google.com/store/apps/details?id=com.stargazer",
        },
        {
          type: "link",
          label: "Stargazer iOS",
          href: "https://apps.apple.com/us/app/stargazer-wallet/id1612326452",
        },
        {
          type: "link",
          label: "EIP-1193",
          href: "https://eips.ethereum.org/EIPS/eip-1193",
        },
      ],
    },
  ],
};
